CREATE TABLE tb_account
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number           VARCHAR(255),
    agency           VARCHAR(255),
    balance          DECIMAL(13, 2),
    additional_limit DECIMAL(13, 2),
    CONSTRAINT pk_tb_account PRIMARY KEY (id)
);