CREATE TABLE tb_card
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number          VARCHAR(255),
    available_limit DECIMAL(13, 2),
    CONSTRAINT pk_tb_card PRIMARY KEY (id)
);

ALTER TABLE tb_card
    ADD CONSTRAINT uc_tb_card_number UNIQUE (number);