CREATE TABLE tb_features
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    icon        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_tb_features PRIMARY KEY (id)
);